TEST_DATASET = [
    # English samples:
    {"text": "Hello, how are you?", "expected_label": "english"},
    {"text": "Good morning, have a great day ahead.", "expected_label": "english"},
    {"text": "What time is the meeting scheduled?", "expected_label": "english"},
    {"text": "Did you finish your homework?", "expected_label": "english"},
    {"text": "I love reading books in my free time.", "expected_label": "english"},
    {"text": "Let's go to the park and have a picnic.", "expected_label": "english"},
    {"text": "The weather is really pleasant today.", "expected_label": "english"},
    {"text": "Can you help me solve this problem?", "expected_label": "english"},
    {"text": "I will arrive in five minutes.", "expected_label": "english"},
    {"text": "Congratulations on your recent success!", "expected_label": "english"},
    # Yoruba samples:
    {"text": "Bawo ni o se wa?", "expected_label": "yoruba"},
    {"text": "Ẹ káàbọ̀, kí ni orúkọ rẹ?", "expected_label": "yoruba"},
    {"text": "Mo n lọ sí ilé ìwé.", "expected_label": "yoruba"},
    {"text": "Jọwọ, fun mi ni omi.", "expected_label": "yoruba"},
    {"text": "Ìrìn àjò rẹ̀ dun gan-an.", "expected_label": "yoruba"},
    {"text": "O ṣeun fún iranlọwọ rẹ.", "expected_label": "yoruba"},
    {"text": "Ẹ̀ káàárọ̀ o.", "expected_label": "yoruba"},
    {"text": "Mo nífẹẹ́ rẹ.", "expected_label": "yoruba"},
    {"text": "Jọ̀wọ́, jẹ́ kí a lọ.", "expected_label": "yoruba"},
    {"text": "O dàbọ̀, tí a ó rí lẹ́yìn.", "expected_label": "yoruba"},
    # Pidgin samples:
    {"text": "How far now?", "expected_label": "pidgin"},
    {"text": "Wetin dey happen?", "expected_label": "pidgin"},
    {"text": "Abeg, come here make we yarn.", "expected_label": "pidgin"},
    {"text": "I dey hungry oh.", "expected_label": "pidgin"},
    {"text": "No wahala, everything dey alright.", "expected_label": "pidgin"},
    {"text": "Wetin you go chop?", "expected_label": "pidgin"},
    {"text": "I no gree make that one happen.", "expected_label": "pidgin"},
    {"text": "How you dey?", "expected_label": "pidgin"},
    {"text": "Make we no dull, time don reach.", "expected_label": "pidgin"},
    {"text": "I dey come, wait small.", "expected_label": "pidgin"},
    # Hausa samples:
    {"text": "Ina kwana?", "expected_label": "hausa"},
    {"text": "Lafiya lau, ya ake ciki?", "expected_label": "hausa"},
    {"text": "Don Allah, kawo min ruwa.", "expected_label": "hausa"},
    {"text": "Zan zo nan da minti biyar.", "expected_label": "hausa"},
    {"text": "Ina jin dadin wannan rana.", "expected_label": "hausa"},
    {"text": "Ka ga abin da ya faru?", "expected_label": "hausa"},
    {"text": "Barka da safiya.", "expected_label": "hausa"},
    {"text": "Ka shirya abincin dare?", "expected_label": "hausa"},
    {"text": "Mun yi nasara a jarrabawar.", "expected_label": "hausa"},
    {"text": "Na gode sosai.", "expected_label": "hausa"},
    # Igbo samples:
    {"text": "Kedu?", "expected_label": "igbo"},
    {"text": "Kedu maka?", "expected_label": "igbo"},
    {"text": "Biko, were m mmiri.", "expected_label": "igbo"},
    {"text": "Anyi ga echi.", "expected_label": "igbo"},
    {"text": "Ijeoma, have a good day.", "expected_label": "igbo"},
    {"text": "Ị bu ezigbo enyi.", "expected_label": "igbo"},
    {"text": "Biko, gwa m eziokwu.", "expected_label": "igbo"},
    {"text": "Ọ dị mma, ka anyi gawa.", "expected_label": "igbo"},
    {"text": "Ekele dịrị gị.", "expected_label": "igbo"},
    {"text": "Anyị ga-ezukọta echi.", "expected_label": "igbo"},
]
